import type { Metadata } from "next";
import { baiJamjuree } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Adrien Miotton · Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${baiJamjuree.className} min-w-2xs antialiased`}>
        {children}
      </body>
    </html>
  );
}
