import type { Metadata } from "next";
import { baiJamjuree } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Adrien Miotton · Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-title" content="Adrien Miotton" />
      </head>
      <body
        className={`${baiJamjuree.className} min-w-2xs scroll-smooth antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
